name: fursal_mobile
description: "SajiloKhel - Your easy sports booking app."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  google_sign_in: ^6.2.2
  cloud_firestore: ^6.1.0
  flutter_riverpod: ^2.6.1
  go_router: ^15.1.2
  google_fonts: ^6.3.0
  flutter_svg: ^2.1.0
  flutter_dotenv: ^5.1.0
  intl: ^0.20.2
  flutter_map: ^8.2.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "logo-assets/logoonly.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "logo-assets/logoonly.png"
    background_color: "#hex_code"
    theme_color: "#hex_code"
  windows:
    generate: true
    image_path: "logo-assets/logoonly.png"
    icon_size: 48 # min:48, max:256, default: 48

flutter_native_splash:
  color: "#FFFFFF"
  image: logo-assets/logoonly.png
  android_12:
    image: logo-assets/logoonly.png
    color: "#FFFFFF"

flutter:
  uses-material-design: true
  assets:
    - .env
