name: fursal_mobile
description: "SajiloKhel - Your easy sports booking app."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  google_sign_in: ^6.2.2
  cloud_firestore: ^6.1.0
  flutter_riverpod: ^2.6.1
  go_router: ^15.1.2
  google_fonts: ^6.3.0
  flutter_svg: ^2.1.0
  flutter_dotenv: ^5.1.0
  intl: ^0.20.2
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  uuid: ^4.2.1
  esewa_flutter: 3.0.1
  flutter_inappwebview: ^6.1.5
  crypto: ^3.0.6
  pdf: ^3.11.3
  printing: ^5.14.2
  qr_flutter: ^4.1.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  open_filex: ^4.7.0
  flutter_local_notifications: ^19.5.0
  device_info_plus: ^11.3.0
  image_picker: ^1.2.1
  firebase_storage: ^13.0.4
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "logo-assets/icon_square.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "logo-assets/icon_square.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "logo-assets/icon_square.png"
    icon_size: 48 # min:48, max:256, default: 48

flutter_native_splash:
  color: "#FFFFFF"
  image: "logo-assets/icon_square.png"
  android_12:
    image: "logo-assets/icon_square.png"
    color: "#FFFFFF"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/logo.png